### ISSUE TITLE
A few questions/issues

### ISSUE THREAD

**Issue by serephus** [LukeYui/elden_ring_item_randomiser#2]
OS: Windows 10
Eden Ring Version: App version 1.04 / Calibration version 1.04.1

1. When play with this mod, the game always show a prompt when item drops including materials. Is this intended or is this a bug?
2. Some item show wrong name and description. seed: 0000005A62ED3F98, merchant kale, stonesword key display as a note. 
3. Some environment models in stormveil castle flicker.

**Comment by serephus** [comment]
And a feature request: Can this mod make glowing skulls drop random item?

**Comment by CaptainsalamiSA** [comment]
Another feature request: can we have a setting that doesnt randomize the drops from killing npcs? Murdering the merchants makes me sad.
